image : mcr.microsoft.com/dotnet/sdk:7.0

variables:
  PROJECTNAME: $CI_PROJECT_TITLE

stages:
  - build
  - test
  - package

build:
  stage: build
  script:
    - dotnet build -c Release
  only:
    - master

test:
  stage: test
  script:
    - dotnet test -c Release
  only:
    - master

package:
  stage: package
  script:
    - dotnet build SFTPServer -c Release -p:Version="${CI_COMMIT_TAG}"
    - dotnet pack SFTPServer -c Release -o artifacts -p:Version="${CI_COMMIT_TAG}"
    - dotnet nuget add source "${CI_API_V4_URL}/projects/${NUGET_CI_PROJECT_ROOT_ID}/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet nuget push "artifacts/*.nupkg" --source gitlab
  artifacts:
    name: $PROJECTNAME-$CI_COMMIT_TAG
    paths:
      - artifacts
    expire_in: 2 days
  only:
    - tags
