namespace SFTPTest;

public enum Status : uint
{
    OK = 0x00,
    EOF = 0x01,
    NO_SUCH_FILE = 0x02,
    PERMISSION_DENIED = 0x03,
    FAILURE = 0x04,
    BAD_MESSAGE = 0x05,
    NO_CONNECTION = 0x06,
    CONNECTION_LOST = 0x07,
    OP_UNSUPPORTED = 0x08, // version 3 - last one
    INVALID_HANDLE = 0x09,
    NO_SUCH_PATH = 0x0A,
    FILE_ALREADY_EXISTS = 0x0B,
    WRITE_PROTECT = 0x0C,
    NO_MEDIA = 0x0D,
    NO_SPACE_ON_FILESYSTEM = 0x0E,
    QUOTA_EXCEEDED = 0x0F,
    UNKNOWN_PRINCIPAL = 0x10,
    LOCK_CONFLICT = 0x11,
    DIR_NOT_EMPTY = 0x12,
    NOT_A_DIRECTORY = 0x13,
    INVALID_FILENAME = 0x14,
    LINK_LOOP = 0x15,
    CANNOT_DELETE = 0x16,
    INVALID_PARAMETER = 0x17,
    FILE_IS_A_DIRECTORY = 0x18,
    BYTE_RANGE_LOCK_CONFLICT = 0x19,
    BYTE_RANGE_LOCK_REFUSED = 0x1A,
    DELETE_PENDING = 0x1B,
    FILE_CORRUPT = 0x1C,
    OWNER_INVALID = 0x1D,
    GROUP_INVALID = 0x1E,
    NO_MATCHING_BYTE_RANGE_LOCK = 0x1F
}